services:
  frontend:
    image: teeks99/mws-frontend:latest
    ports:
      - "5125:80"
    depends_on:
      - api

  api:
    image: teeks99/mws-backend:latest
    ports:
      - "5126:8000"
    env_file:
      - .env
    environment:
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - redis

  redis:
    image: redis:7-alpine
    volumes:
      - redis_data:/data

volumes:
  redis_data: