version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "5125:80"
    depends_on:
      - api

  api:
    build:
      context: ./backend
    ports:
      - "5126:8000"
    volumes:
      - ./backend:/app
    env_file:
      - .env
    environment:
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - redis

  redis:
    image: redis:7-alpine
    volumes:
      - redis_data:/data

volumes:
  redis_data:
